services:
  backend:
    build: .
    container_name: uzchess-backend
    command: >
      sh -c "npx typeorm -d ./dist/data-source.js migration:run && node dist/main.js"
    ports:
      - "8000:8000"
    restart: always
    networks:
      - uzchess
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:18-alpine
    container_name: uzchess-database
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - uzchess
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: uzchess_n8
networks:
  uzchess:
    driver: bridge